STUPID_UNITS = \
    ["kilograms",
     "liters",
     "gallons",
     "pounds",
     "buckets",
     "teaspoons",
     "truck loads",
     "cups",
     "packets",
     "sacks",
     "atoms",
     "cubic meters",
     "grains",
     "backpacks",
     "boxes",
     "meters",
     "handfuls",
     "square kilometers",
     "feet",
     "astronomic units",
     "seconds",
     "light years",
     "gigawatts",
     "bytes",
     "angstroms",
     "oceans",
     "brown paperbags",
     "socks",
     "handbags",
     "elephants' butts",
     "electronvolts",
     "tons of TNT equivalent",
     "FLOPS",
     "ticks",
     "hair's breadths",
     "microns",
     "mountains",
     "gogols",
     "beer bottles",
     "envelopes",
     "corpse bags",
     "coffins",
     "urns",
     "buttloads",
     "ashtrays",
     "black holes",
     "neutron stars",
     "lawnmowers",
     "melons",
     "megahertz",
     "floppy disks",
     "VHS tapes",
     "hard drives",
     "server racks",
     "elevators",
     "airbags",
     "cans",
     "sieves",
     "sieverts",
     "bars",
     "photographs",
     "test tubes",
     "catheter bags",
     "pallets",
     "aardvarks",
     "unicorns",
     "drops",
     "excel sheets",
     "kegs",
     "skyscrapers",
     "bottomless pits",
     "trombones",
     "chambers",
     "fountains",
     "limousines",
     "shopping carts",
     ]
